cache:
  key: "vendor-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA"
  paths:
    - vendor

stages:
  - build

# Сборка проекта
build:
  stage: build
  script:
    # Composer
    - '[[ -f composer.json ]] && composer install --prefer-dist --no-progress'

