variables:
  # Заявка
  TASK_ID: ''

stages:
  - deploy

# Выкладка ветки для теста
deploy to staging:
  stage: deploy
  only:
    - /^feature\/.*$/
  except:
    - feature/master
    - develop
    - dev
    - master
  environment:
    name: test/${CI_COMMIT_REF_SLUG}
    url: ${URL_TEST}${CI_COMMIT_REF_SLUG}/index.php
    on_stop: remove in test
  script:
    # build script
    # ...
  when: manual

# Удаление ветки для теста
remove in develop:
  stage: deploy
  only:
    - /^feature\/.*$/
  except:
    - feature/master
    - develop
    - dev
  environment:
    name: develop/${CI_COMMIT_REF_SLUG}
    action: stop
  script:
    # delete script
    # ...
  when: manual